{
 "title": "General Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(rts_gc_cpu_ms[$__interval])"
    }
   ]
  },
  {
   "title": "Num Blocks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int"
    }
   ]
  },
  {
   "title": "Num Epochs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "cardano_node_metrics_epoch_int{}"
    }
   ]
  }
 ]
}