global:
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'cardano' # To scrape data from the cardano node
    scrape_interval: 5s
    static_configs:
      - targets: ['cardano-node:12798']
