global:
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'cardano' # To scrape data from the cardano node
    scrape_interval: 5s
    static_configs:
      - targets: ['cardano-node:12798']
  - job_name: 'cardano-postgres-db' # To scrape data from the cardano node
    scrape_interval: 15s
    static_configs:
      - targets: ['postgres-exporter:9187']
  - job_name: 'node-exporter' # To scrape data from the cardano node
    scrape_interval: 15s
    static_configs:
      - targets: ['node-exporter:9100']
